### ISSUE TITLE
Wards radius problems

### ISSUE THREAD

**Issue by mwjster** [AzumattDev/WardIsLove#31]
I am setting up a new server for public use and it seems that no matter what i set the radius of the ward to it is still effecting its maximum range. so i am just trying to protect my house at say 30% radius. the effects are still being seen all the way to where it would be if it was set to 100%. this is with the latest version of the mod and the latest valheim/valheim plus updates installed.

**Comment by AzumattDev** [comment]
Your issue is ValheimPlus. It changes all effect area sizes.

**Comment by mwjster** [comment]
is there a config setting in valheim plus that can be changed to stop this?
