### ISSUE TITLE
Wards non-functional since recent update

### ISSUE THREAD

**Issue by Mistermycelium** [AzumattDev/WardIsLove#44]
Since update 3.3.0 all wards have been dysfunctional on our public server. Loading a previous version of the world locally with version 3.4 installed shows the same behavior. 
Mod pack: https://valheim.thunderstore.io/package/VikingHaul/VikingHaul/

logs attached from private hosted world:
[LogOutput.log](https://github.com/AzumattDev/WardIsLove/files/12923360/LogOutput.log)
[Player.log](https://github.com/AzumattDev/WardIsLove/files/12923361/Player.log)

**Comment by AzumattDev** [comment]
Hopefully this is fixed in 3.4.1

**Comment by AzumattDev** [comment]
> Testing in the privately hosted world still has the same issue.

Then please describe the issue in more detail. The logs you have provided appear to be either incomplete or not showing errors.

**Comment by AzumattDev** [comment]
Inactive post
