### ISSUE TITLE
Mod not compatible with latest verison

### ISSUE THREAD

**Issue by olepg** [AzumattDev/WardIsLove#49]
Mod seems to be uncompatible with latest valheim version:

![image](https://github.com/AzumattDev/WardIsLove/assets/27433531/73e7d38f-eed3-4f64-a315-1932a0fbb397)

**Comment by AzumattDev** [comment]
The mod works fine on the latest version of the game.

**Comment by olepg** [comment]
Is there a way for me to read out logs / error msg?

**Comment by AzumattDev** [comment]
Yes, read your BepInEx/LogOutput.log file and make sure you are on the latest released version of the game 0.217.38

**Comment by olepg** [comment]
Here's my valheim version:
![image](https://github.com/AzumattDev/WardIsLove/assets/27433531/3ee636b9-a3b3-4276-9962-0ff720a6bb9a)

LogOutput.log:
```text
[Message:   BepInEx] BepInEx 5.4.22.0 - valheim (11/11/2023 5:35:17 AM)
[Info   :   BepInEx] Running under Unity v2022.3.12.5236448
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [WardIsLove 3.5.1]
[Message:   BepInEx] Chainloader startup complete
[Info   :WardIsLove] WardIsLove [3.5.1] is up to date.
```

**Comment by olepg** [comment]
The issue has resolved itself with the patch today. However I'm getting a message that I'm running an older version. Even though I'm running 3.5.1:
![image](https://github.com/AzumattDev/WardIsLove/assets/27433531/5c36259d-3413-41f1-99a1-8fc24b0710db)

**Comment by AzumattDev** [comment]
No clue how it would fix itself unless you're using a built version for something else. The mod needed updates for the 0.217.46 (that I haven't released)

**Comment by olepg** [comment]
yeah, I have no clue either. Thanks for your mods though!
