### ISSUE TITLE
Players not being added

### ISSUE THREAD

**Issue by 7Dagoth** [AzumattDev/WardIsLove#54]
Hello!
I can't add players through the GUI. This is a conflict with another mod? The console shows this error:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
WardIsLove.Util.UI.WardGUIUtil.AddPermitted () (at <55438ee051b145f0a0d5466c17f1ba77>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.UI.Button.Press () (at <c784ba61915748ee8776f4834d413c9a>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <c784ba61915748ee8776f4834d413c9a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <c784ba61915748ee8776f4834d413c9a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <c784ba61915748ee8776f4834d413c9a>:0)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by AzumattDev** [comment]
Likely a conflict, yes.

**Comment by 7Dagoth** [comment]
Ok, I'll try to figure this out, thx

**Comment by AzumattDev** [comment]
Stale
