### ISSUE TITLE
Ship Interaction Toggle Not Functioning As Intended

### ISSUE THREAD

**Issue by Khordus** [AzumattDev/WardIsLove#8]
Ship Interaction on the ward does not function properly. If you have it set to OFF, then attempting to use a ship rudder shows "no access"; but, if that is set to ON, it appears as though you can use the ship rudder, but hitting E/interact results in no action.

Tested in fresh Thunderstore modpack using only WIL and BepInEx to confirm issue is not mod conflict.

**Comment by AzumattDev** [comment]
Fixed in my dev branch.
